[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "seelaikaari.com/*"
  to = "https://www.seelaikaari.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "www.seelaikaari.com/*"
  to = "https://www.seelaikaari.com/:splat"
  status = 301
  force = true
